#############################################################################
# Makefile for building: Motorrad.app/Contents/MacOS/Motorrad
# Generated by qmake (3.1) (Qt 5.12.10)
# Project:  Motorrad.pro
# Template: app
# Command: /Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/bin/qmake -o Makefile Motorrad.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers -I../Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers -I../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../Qt5.12.10/5.12.10/clang_64/mkspecs/macx-clang -F/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib
QMAKE         = /Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Motorrad1.0.0
DISTDIR = /Users/yunhaowu/Motorrad/.tmp/Motorrad1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = choosemotorradwindow.cpp \
		chooseweatherwindow.cpp \
		imgbutton.cpp \
		main.cpp \
		mainwindow.cpp \
		playwindow.cpp \
		profilewindow.cpp moc_choosemotorradwindow.cpp \
		moc_chooseweatherwindow.cpp \
		moc_imgbutton.cpp \
		moc_mainwindow.cpp \
		moc_playwindow.cpp \
		moc_profilewindow.cpp
OBJECTS       = choosemotorradwindow.o \
		chooseweatherwindow.o \
		imgbutton.o \
		main.o \
		mainwindow.o \
		playwindow.o \
		profilewindow.o \
		moc_choosemotorradwindow.o \
		moc_chooseweatherwindow.o \
		moc_imgbutton.o \
		moc_mainwindow.o \
		moc_playwindow.o \
		moc_profilewindow.o
DIST          = ../Qt5.12.10/5.12.10/clang_64/mkspecs/features/spec_pre.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/qdevice.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/device_config.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/unix.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/mac.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/macx.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/sanitize.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/gcc-base.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/clang.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/clang-mac.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/qconfig.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/qt_functions.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/qt_config.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/spec_post.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/toolchain.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/toolchain.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/default_pre.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/resolve_config.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/default_post.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/qml_debug.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/mac.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/warn_on.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/qt.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/resources.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/moc.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/uic.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/unix/thread.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/qmake_use.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/file_copies.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/rez.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/exceptions.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/yacc.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/lex.prf \
		Motorrad.pro choosemotorradwindow.h \
		chooseweatherwindow.h \
		imgbutton.h \
		mainwindow.h \
		playwindow.h \
		profilewindow.h choosemotorradwindow.cpp \
		chooseweatherwindow.cpp \
		imgbutton.cpp \
		main.cpp \
		mainwindow.cpp \
		playwindow.cpp \
		profilewindow.cpp
QMAKE_TARGET  = Motorrad
DESTDIR       = 
TARGET        = Motorrad.app/Contents/MacOS/Motorrad

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 11.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/yunhaowu/Motorrad/Motorrad.pro


include /Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Motorrad.app/Contents/MacOS/Motorrad: ui_PlayWindow.h ui_ShowProfileWindow.h ui_choosemotorrad.h ui_chooseweatherwindow.h ui_mainwindow.h $(OBJECTS)  
	@test -d Motorrad.app/Contents/MacOS/ || mkdir -p Motorrad.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Motorrad.pro ../Qt5.12.10/5.12.10/clang_64/mkspecs/macx-clang/qmake.conf ../Qt5.12.10/5.12.10/clang_64/mkspecs/features/spec_pre.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/qdevice.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/device_config.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/unix.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/mac.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/macx.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/sanitize.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/gcc-base.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/clang.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/common/clang-mac.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/qconfig.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/qt_functions.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/qt_config.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/spec_post.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/toolchain.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/toolchain.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/default_pre.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/resolve_config.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/default_post.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/qml_debug.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/mac.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/warn_on.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/qt.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/resources.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/moc.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/uic.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/unix/thread.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/qmake_use.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/file_copies.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/rez.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/exceptions.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/yacc.prf \
		../Qt5.12.10/5.12.10/clang_64/mkspecs/features/lex.prf \
		Motorrad.pro \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/QtGui.prl \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Motorrad.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/spec_pre.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/qdevice.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/device_config.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/common/unix.conf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/common/mac.conf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/common/macx.conf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/common/sanitize.conf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/common/gcc-base.conf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/common/gcc-base-mac.conf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/common/clang.conf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/common/clang-mac.conf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/qconfig.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_core.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_designer.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_gui.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_help.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_location.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_network.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qml.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quick.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_sql.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_svg.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_webview.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_xml.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/qt_functions.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/qt_config.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/macx-clang/qmake.conf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/spec_post.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/exclusive_builds.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/sdk.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/toolchain.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/toolchain.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/default_pre.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/default_pre.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/resolve_config.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/default_post.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/default_post.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/objective_c.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/qml_debug.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/mac.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/warn_on.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/qt.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/resources.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/moc.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/unix/opengl.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/uic.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/unix/thread.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/qmake_use.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/file_copies.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/rez.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/testcase_targets.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/exceptions.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/yacc.prf:
../Qt5.12.10/5.12.10/clang_64/mkspecs/features/lex.prf:
Motorrad.pro:
../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/QtGui.prl:
../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Motorrad.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

Motorrad.app/Contents/PkgInfo: 
	@test -d Motorrad.app/Contents || mkdir -p Motorrad.app/Contents
	@$(DEL_FILE) Motorrad.app/Contents/PkgInfo
	@echo "APPL????" > Motorrad.app/Contents/PkgInfo
Motorrad.app/Contents/Resources/empty.lproj: 
	@test -d Motorrad.app/Contents/Resources || mkdir -p Motorrad.app/Contents/Resources
	@touch Motorrad.app/Contents/Resources/empty.lproj
	
Motorrad.app/Contents/Info.plist: 
	@test -d Motorrad.app/Contents || mkdir -p Motorrad.app/Contents
	@$(DEL_FILE) Motorrad.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,Cpp.Motorrad,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},Cpp.Motorrad,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Motorrad,g" -e "s,@LIBRARY@,Motorrad,g" -e "s,\$${EXECUTABLE_NAME},Motorrad,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../Qt5.12.10/5.12.10/clang_64/mkspecs/macx-clang/Info.plist.app >Motorrad.app/Contents/Info.plist

all: Makefile \
		Motorrad.app/Contents/PkgInfo \
		Motorrad.app/Contents/Resources/empty.lproj \
		Motorrad.app/Contents/Info.plist Motorrad.app/Contents/MacOS/Motorrad

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../Qt5.12.10/5.12.10/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents choosemotorradwindow.h chooseweatherwindow.h imgbutton.h mainwindow.h playwindow.h profilewindow.h $(DISTDIR)/
	$(COPY_FILE) --parents choosemotorradwindow.cpp chooseweatherwindow.cpp imgbutton.cpp main.cpp mainwindow.cpp playwindow.cpp profilewindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents PlayWindow.ui ShowProfileWindow.ui choosemotorrad.ui chooseweatherwindow.ui mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Motorrad.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../Qt5.12.10/5.12.10/clang_64/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h ../Qt5.12.10/5.12.10/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_choosemotorradwindow.cpp moc_chooseweatherwindow.cpp moc_imgbutton.cpp moc_mainwindow.cpp moc_playwindow.cpp moc_profilewindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_choosemotorradwindow.cpp moc_chooseweatherwindow.cpp moc_imgbutton.cpp moc_mainwindow.cpp moc_playwindow.cpp moc_profilewindow.cpp
moc_choosemotorradwindow.cpp: choosemotorradwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		moc_predefs.h \
		../Qt5.12.10/5.12.10/clang_64/bin/moc
	/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/bin/moc $(DEFINES) --include /Users/yunhaowu/Motorrad/moc_predefs.h -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/mkspecs/macx-clang -I/Users/yunhaowu/Motorrad -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib choosemotorradwindow.h -o moc_choosemotorradwindow.cpp

moc_chooseweatherwindow.cpp: chooseweatherwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		moc_predefs.h \
		../Qt5.12.10/5.12.10/clang_64/bin/moc
	/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/bin/moc $(DEFINES) --include /Users/yunhaowu/Motorrad/moc_predefs.h -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/mkspecs/macx-clang -I/Users/yunhaowu/Motorrad -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib chooseweatherwindow.h -o moc_chooseweatherwindow.cpp

moc_imgbutton.cpp: imgbutton.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		moc_predefs.h \
		../Qt5.12.10/5.12.10/clang_64/bin/moc
	/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/bin/moc $(DEFINES) --include /Users/yunhaowu/Motorrad/moc_predefs.h -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/mkspecs/macx-clang -I/Users/yunhaowu/Motorrad -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib imgbutton.h -o moc_imgbutton.cpp

moc_mainwindow.cpp: mainwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		chooseweatherwindow.h \
		choosemotorradwindow.h \
		profilewindow.h \
		playwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/QTimer \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		moc_predefs.h \
		../Qt5.12.10/5.12.10/clang_64/bin/moc
	/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/bin/moc $(DEFINES) --include /Users/yunhaowu/Motorrad/moc_predefs.h -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/mkspecs/macx-clang -I/Users/yunhaowu/Motorrad -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_playwindow.cpp: playwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/QTimer \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		moc_predefs.h \
		../Qt5.12.10/5.12.10/clang_64/bin/moc
	/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/bin/moc $(DEFINES) --include /Users/yunhaowu/Motorrad/moc_predefs.h -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/mkspecs/macx-clang -I/Users/yunhaowu/Motorrad -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib playwindow.h -o moc_playwindow.cpp

moc_profilewindow.cpp: profilewindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		moc_predefs.h \
		../Qt5.12.10/5.12.10/clang_64/bin/moc
	/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/bin/moc $(DEFINES) --include /Users/yunhaowu/Motorrad/moc_predefs.h -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/mkspecs/macx-clang -I/Users/yunhaowu/Motorrad -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers -I/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/lib profilewindow.h -o moc_profilewindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_PlayWindow.h ui_ShowProfileWindow.h ui_choosemotorrad.h ui_chooseweatherwindow.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_PlayWindow.h ui_ShowProfileWindow.h ui_choosemotorrad.h ui_chooseweatherwindow.h ui_mainwindow.h
ui_PlayWindow.h: PlayWindow.ui \
		../Qt5.12.10/5.12.10/clang_64/bin/uic
	/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/bin/uic PlayWindow.ui -o ui_PlayWindow.h

ui_ShowProfileWindow.h: ShowProfileWindow.ui \
		../Qt5.12.10/5.12.10/clang_64/bin/uic
	/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/bin/uic ShowProfileWindow.ui -o ui_ShowProfileWindow.h

ui_choosemotorrad.h: choosemotorrad.ui \
		../Qt5.12.10/5.12.10/clang_64/bin/uic
	/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/bin/uic choosemotorrad.ui -o ui_choosemotorrad.h

ui_chooseweatherwindow.h: chooseweatherwindow.ui \
		../Qt5.12.10/5.12.10/clang_64/bin/uic
	/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/bin/uic chooseweatherwindow.ui -o ui_chooseweatherwindow.h

ui_mainwindow.h: mainwindow.ui \
		../Qt5.12.10/5.12.10/clang_64/bin/uic
	/Users/yunhaowu/Qt5.12.10/5.12.10/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

choosemotorradwindow.o: choosemotorradwindow.cpp choosemotorradwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/QTimer \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers/QPainter \
		../Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QStyle \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/QDebug \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		imgbutton.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o choosemotorradwindow.o choosemotorradwindow.cpp

chooseweatherwindow.o: chooseweatherwindow.cpp chooseweatherwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_chooseweatherwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/QTimer \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers/QPainter \
		../Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QStyle \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/QDebug \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		imgbutton.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chooseweatherwindow.o chooseweatherwindow.cpp

imgbutton.o: imgbutton.cpp imgbutton.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/QDebug \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/QPropertyAnimation \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/qpropertyanimation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgbutton.o imgbutton.cpp

main.o: main.cpp mainwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		chooseweatherwindow.h \
		choosemotorradwindow.h \
		profilewindow.h \
		playwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/QTimer \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		chooseweatherwindow.h \
		choosemotorradwindow.h \
		profilewindow.h \
		playwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/QTimer \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		ui_mainwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers/QPainter \
		../Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		imgbutton.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

playwindow.o: playwindow.cpp playwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/QTimer \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers/QPainter \
		../Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/QDebug \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/QStack \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/qstack.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/QPair \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/qpair.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../Qt5.12.10/5.12.10/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/QPropertyAnimation \
		../Qt5.12.10/5.12.10/clang_64/lib/QtCore.framework/Headers/qpropertyanimation.h \
		imgbutton.h \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../Qt5.12.10/5.12.10/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playwindow.o playwindow.cpp

profilewindow.o: profilewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profilewindow.o profilewindow.cpp

moc_choosemotorradwindow.o: moc_choosemotorradwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_choosemotorradwindow.o moc_choosemotorradwindow.cpp

moc_chooseweatherwindow.o: moc_chooseweatherwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chooseweatherwindow.o moc_chooseweatherwindow.cpp

moc_imgbutton.o: moc_imgbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imgbutton.o moc_imgbutton.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_playwindow.o: moc_playwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_playwindow.o moc_playwindow.cpp

moc_profilewindow.o: moc_profilewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profilewindow.o moc_profilewindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Motorrad/bin || mkdir -p $(INSTALL_ROOT)/opt/Motorrad/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Motorrad/bin/Motorrad.app
	
	-$(QINSTALL) Motorrad.app $(INSTALL_ROOT)/opt/Motorrad/bin/Motorrad.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Motorrad/bin/Motorrad.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Motorrad/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

